# Generated by Django 5.2.3 on 2025-07-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyshow_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Drama', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='', upload_to='movie_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.CharField(default=7.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
