# Generated by Django 5.2.3 on 2025-08-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyshow_app', '0007_movie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
