# Generated by Django 5.2.3 on 2025-08-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyshow_app', '0008_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
    ]
