# Generated by Django 5.2.3 on 2025-08-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyshow_app', '0013_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
